# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menupage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


#CHANGE !

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtMultimedia import QMediaPlayer, QMediaContent
from PyQt5.QtCore import QUrl
import os

from pathlib import Path, PureWindowsPath
from os.path import dirname, abspath

imagesPath = dirname(dirname(abspath(__file__))) + "/images/"
realImagesPath = []
for i in imagesPath:
    realImagesPath.append(i)

del(realImagesPath[0])
del(realImagesPath[0])

for i in range(len(realImagesPath)):
    if realImagesPath[i] == "\\":
        realImagesPath[i] = "/"

imagesPath = "".join(realImagesPath)

class Ui_startPage(object):
    def setupUi(self, startPage):
        startPage.setObjectName("startPage")
        startPage.resize(1600, 900)
        startPage.setMaximumSize(QtCore.QSize(1600, 900))

        widthOfTitle = 500        
        self.label = QtWidgets.QLabel(startPage)
        self.label.setGeometry(QtCore.QRect(800 - widthOfTitle//2, 50, widthOfTitle + 30, 100))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(imagesPath + "MatricesQuiz.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.reviseButton = QtWidgets.QPushButton(startPage)
        buttonWidth = 380
        self.reviseButton.setGeometry(QtCore.QRect(100, 800, buttonWidth - 100, 90))
        self.reviseButton.setText("")
        self.reviseButton.setObjectName("reviseButton")
        self.reviseButton.setAutoFillBackground(False)
        self.reviseButton.setStyleSheet("border: 1px solid #000000;\n"
"border-image: url(" + str(imagesPath) + "Revise.png) 0 0 0 0 stretch stretch;")


        self.startButton = QtWidgets.QPushButton(startPage)
        buttonWidth = 380
        self.startButton.setGeometry(QtCore.QRect(1600 - buttonWidth, 800, buttonWidth - 100, 90))
        self.startButton.setText("")
        self.startButton.setObjectName("startButton")
        self.startButton.setAutoFillBackground(False)
        self.startButton.setStyleSheet("border: 1px solid #000000;\n"
"border-image: url(" + str(imagesPath) + "Start.png) 0 0 0 0 stretch stretch;")

        self.background = QtWidgets.QLabel(startPage)
        self.background.setGeometry(QtCore.QRect(0, 0, 1600, 900))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap(imagesPath + "Background.png"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        
        self.matrixImage = QtWidgets.QLabel(startPage)
        self.matrixImage.setGeometry(QtCore.QRect(400, 200, 800, 500)) #321,191
        self.matrixImage.setText("")
        self.matrixImage.setPixmap(QtGui.QPixmap(imagesPath + "menuImage.png"))
        self.matrixImage.setScaledContents(True)
        self.matrixImage.setObjectName("matrixImage")

        #self.startButton.clicked.connect(self.playfile)

        self.background.raise_()
        self.label.raise_()
        self.reviseButton.raise_()
        self.startButton.raise_()
        self.matrixImage.raise_()

        self.player = QMediaPlayer()

        '''
        startPage.setToolTipDuration(-10)
        self.verticalLayout = QtWidgets.QVBoxLayout(startPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(startPage)
        self.label.setMaximumSize(QtCore.QSize(1000000, 200))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        
        self.verticalLayout.addWidget(self.quiz)
       
        self.verticalLayout.addWidget(self.pushButton_3)

        self.retranslateUi(startPage)
        QtCore.QMetaObject.connectSlotsByName(startPage)'''

    def playfile(self):
        url = QUrl.fromLocalFile("samplesound.wav")
        content = QMediaContent(url)

        self.player.setMedia(content)
        self.player.setVolume(50)
        self.player.play()
        print("click!!!")

    
    def retranslateUi(self, startPage):
        _translate = QtCore.QCoreApplication.translate
        startPage.setWindowTitle(_translate("startPage", "Frame"))
        self.label.setText(_translate("startPage", "Matrices Quiz"))
        self.quiz.setText(_translate("startPage", "Quiz"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    startPage = QtWidgets.QFrame()
    ui = Ui_startPage()
    ui.setupUi(startPage)
    ui.playfile()
    startPage.show()
    sys.exit(app.exec_())
