# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resultsPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#CHANGE!

from turtle import width
from PyQt5 import QtCore, QtGui, QtWidgets

from pathlib import Path, PureWindowsPath
from os.path import dirname, abspath

imagesPath = dirname(dirname(abspath(__file__))) + "/images/"
realImagesPath = []
for i in imagesPath:
    realImagesPath.append(i)

del(realImagesPath[0])
del(realImagesPath[0])

for i in range(len(realImagesPath)):
    if realImagesPath[i] == "\\":
        realImagesPath[i] = "/"

imagesPath = "".join(realImagesPath)

class Ui_results(object):
    def setupUi(self, results):
        results.setObjectName("results")
        results.resize(1600, 900)
        results.setMaximumSize(QtCore.QSize(1600, 900))

        self.test = 8080
        
        self.retryButton = QtWidgets.QPushButton(results)
        buttonWidth = 380
        self.retryButton.setGeometry(QtCore.QRect(1600 - buttonWidth, 800, buttonWidth - 100, 90))
        self.retryButton.setText("")
        self.retryButton.setObjectName("retryButton")
        self.retryButton.setAutoFillBackground(False)
        self.retryButton.setStyleSheet("border: 1px solid #000000;\n"
"border-image: url(" + str(imagesPath) + "retry.png) 0 0 0 0 stretch stretch;")

        self.label_5 = QtWidgets.QLabel(results)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 1600, 900))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(imagesPath + "Background.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_5.raise_()
        
        self.reviseButton = QtWidgets.QPushButton(results)
        buttonWidth = 380
        self.reviseButton.setGeometry(QtCore.QRect(100, 800, buttonWidth - 100, 90))
        self.reviseButton.setText("")
        self.reviseButton.setObjectName("reviseButton")
        self.reviseButton.setAutoFillBackground(False)
        self.reviseButton.setStyleSheet("border: 1px solid #000000;\n"
"border-image: url(" + str(imagesPath) + "revise.png) 0 0 0 0 stretch stretch;")

        self.resultsTitle = QtWidgets.QLabel(results)
        widthOfTitle = 500
        self.resultsTitle.setGeometry(QtCore.QRect(800 - widthOfTitle//2, 50, widthOfTitle, 100))
        self.resultsTitle.setText("")
        self.resultsTitle.setPixmap(QtGui.QPixmap(imagesPath + "results.png"))
        self.resultsTitle.setScaledContents(True)
        self.resultsTitle.setObjectName("resultsTitle")
        
        buttonWidth = 380
        self.backButton = QtWidgets.QPushButton(results)
        self.backButton.setGeometry(QtCore.QRect(680, 290, 250, 70))
        self.backButton.setText("")
        self.backButton.setObjectName("backButton")
        self.backButton.setAutoFillBackground(False)
        self.backButton.setStyleSheet("border: 1px solid #000000;\n"
"border-image: url(" + str(imagesPath) + "back.png) 0 0 0 0 stretch stretch;")
        
        buttonWidth = 380
        self.nextButton = QtWidgets.QPushButton(results)
        self.nextButton.setGeometry(QtCore.QRect(1080, 290, 250, 70))
        self.nextButton.setText("")
        self.nextButton.setObjectName("nextButton")
        self.nextButton.setAutoFillBackground(False)
        self.nextButton.setStyleSheet("border: 1px solid #000000;\n"
"border-image: url(" + str(imagesPath) + "Next.png) 0 0 0 0 stretch stretch;")

        self.correctnessHeader = QtWidgets.QLabel(results)
        self.correctnessHeader.setGeometry(QtCore.QRect(1040, 400, 330, 100))
        self.correctnessHeader.setText("")
        self.correctnessHeader.setPixmap(QtGui.QPixmap(imagesPath + "correct.png"))
        self.correctnessHeader.setScaledContents(True)
        self.correctnessHeader.setObjectName("correctnessHeader")

        self.viewQuestion = QtWidgets.QPushButton(results)
        buttonWidth = 350
        self.viewQuestion.setGeometry(QtCore.QRect(800 - buttonWidth//2, 500, buttonWidth, 120))
        self.viewQuestion.setText("")
        self.viewQuestion.setObjectName("viewQuestion")
        self.viewQuestion.setAutoFillBackground(False)
        self.viewQuestion.setStyleSheet("border: 1px solid #000000;\n"
"border-image: url(" + str(imagesPath) + "viewQuestion.png) 0 0 0 0 stretch stretch;")

        self.userAns = QtWidgets.QTextBrowser(results)
        self.userAns.setGeometry(QtCore.QRect(200, 600, 300, 100))
        self.userAns.setText("Your Answer: ")
        self.userAns.setStyleSheet("border: 1px solid #000000;\n"
"border-image: url(" + str(imagesPath) + "metal.png) 0 0 0 0 stretch stretch;")
        self.userAns.setAlignment(QtCore.Qt.AlignCenter)
        self.userAns.setObjectName("userAns")
        self.userAns.raise_()

        self.correctAns = QtWidgets.QTextBrowser(results)
        self.correctAns.setGeometry(QtCore.QRect(910 + 300//2, 600, 300, 100))
        self.correctAns.setText("Correct Answer: ")
        self.correctAns.setStyleSheet("border: 1px solid #000000;\n"
"border-image: url(" + str(imagesPath) + "metal.png) 0 0 0 0 stretch stretch;")
        self.correctAns.setAlignment(QtCore.Qt.AlignCenter)
        self.correctAns.setObjectName("correctAns")
        self.correctAns.raise_()

        self.questionHeader = QtWidgets.QLabel(results)
        labelWidth = 380
        self.questionHeader.setGeometry(QtCore.QRect(800 - labelWidth//2, 150, labelWidth, 90))
        self.questionHeader.setText("")
        self.questionHeader.setPixmap(QtGui.QPixmap(imagesPath + "question.png"))
        self.questionHeader.setScaledContents(True)
        self.questionHeader.setObjectName("questionHeader")

        self.leaderboardButton = QtWidgets.QPushButton(results)
        buttonWidth = 500
        self.leaderboardButton.setGeometry(QtCore.QRect(800 - buttonWidth//2, 800, buttonWidth, 90))
        self.leaderboardButton.setText("")
        self.leaderboardButton.setObjectName("leaderboardButton")
        self.leaderboardButton.setAutoFillBackground(False)
        self.leaderboardButton.setStyleSheet("border: 1px solid #000000;\n"
"border-image: url(" + str(imagesPath) + "leaderboard.png) 0 0 0 0 stretch stretch;")

        questionNumber, totalQuestions = 10, 10

        offsetX, offsetY = -900, 500

        ''' self.yourScoreDigit = QtWidgets.QLabel(results)
        self.yourScoreDigit.setGeometry(QtCore.QRect(1100 + offsetX, 50 + offsetY, 70, 100)) 
        self.yourScoreDigit.setText("")
        self.yourScoreDigit.setPixmap(QtGui.QPixmap(imagesPath + str(questionNumber//10)  + ".png"))
        self.yourScoreDigit.setScaledContents(True)
        self.yourScoreDigit.setObjectName("yourScoreDigit")
        self.yourScoreDigit.raise_()'''

        '''self.yourScoreDigit1 = QtWidgets.QLabel(results)
        self.yourScoreDigit1.setGeometry(QtCore.QRect(1000 + offsetX, 50 + offsetY, 70, 100)) 
        self.yourScoreDigit1.setText("")
        self.yourScoreDigit1.setPixmap(QtGui.QPixmap(imagesPath + str(questionNumber%10)  + ".png"))
        self.yourScoreDigit1.setScaledContents(True)
        self.yourScoreDigit1.setObjectName("yourScoreDigit1")
        self.yourScoreDigit1.raise_()'''

        '''self.yourTotalQuestionsDigit = QtWidgets.QLabel(results)
        self.yourTotalQuestionsDigit.setGeometry(QtCore.QRect(1270 + offsetX, 50 + offsetY, 70, 100))
        self.yourTotalQuestionsDigit.setText("")
        self.yourTotalQuestionsDigit.setPixmap(QtGui.QPixmap(imagesPath + str(totalQuestions//10) + ".png"))
        self.yourTotalQuestionsDigit.setScaledContents(True)
        self.yourTotalQuestionsDigit.setObjectName("yourTotalQuestionsDigit")
        self.yourTotalQuestionsDigit.raise_()'''

        '''self.yourTotalQuestionsDigit1 = QtWidgets.QLabel(results)
        self.yourTotalQuestionsDigit1.setGeometry(QtCore.QRect(1320 + offsetX, 50 + offsetY, 70, 100))
        self.yourTotalQuestionsDigit1.setText("")
        self.yourTotalQuestionsDigit1.setPixmap(QtGui.QPixmap(imagesPath + str(totalQuestions%10) + ".png"))
        self.yourTotalQuestionsDigit1.setScaledContents(True)
        self.yourTotalQuestionsDigit1.setObjectName("yourTotalQuestionsDigit1")
        self.yourTotalQuestionsDigit1.raise_()'''

        '''self.slashTitle = QtWidgets.QLabel(results)
        self.slashTitle.setGeometry(QtCore.QRect(1225 + offsetX, 50 + offsetY, 50, 100))
        self.slashTitle.setText("")
        self.slashTitle.setPixmap(QtGui.QPixmap(imagesPath + "slash.png"))
        self.slashTitle.setScaledContents(True)
        self.slashTitle.setObjectName("slashTitle")
        self.slashTitle.raise_()'''

        self.currentQuestionDigit = QtWidgets.QLabel(results)
        self.currentQuestionDigit.setGeometry(QtCore.QRect(1100, 150, 70, 100)) 
        self.currentQuestionDigit.setText("")
        self.currentQuestionDigit.setPixmap(QtGui.QPixmap(imagesPath + str(questionNumber//10)  + ".png"))
        self.currentQuestionDigit.setScaledContents(True)
        self.currentQuestionDigit.setObjectName("currentQuestionDigit")

        self.currentQuestionDigit1 = QtWidgets.QLabel(results)
        self.currentQuestionDigit1.setGeometry(QtCore.QRect(1160, 150, 70, 100)) 
        self.currentQuestionDigit1.setText("")
        self.currentQuestionDigit1.setPixmap(QtGui.QPixmap(imagesPath + str(questionNumber%10)  + ".png"))
        self.currentQuestionDigit1.setScaledContents(True)
        self.currentQuestionDigit1.setObjectName("currentQuestionDigit1")

        self.totalQuestionsDigit = QtWidgets.QLabel(results)
        self.totalQuestionsDigit.setGeometry(QtCore.QRect(1270, 150, 70, 100))
        self.totalQuestionsDigit.setText("")
        self.totalQuestionsDigit.setPixmap(QtGui.QPixmap(imagesPath + str(totalQuestions//10) + ".png"))
        self.totalQuestionsDigit.setScaledContents(True)
        self.totalQuestionsDigit.setObjectName("totalQuestionsDigit")

        self.totalQuestionsDigit1 = QtWidgets.QLabel(results)
        self.totalQuestionsDigit1.setGeometry(QtCore.QRect(1320, 150, 70, 100))
        self.totalQuestionsDigit1.setText("")
        self.totalQuestionsDigit1.setPixmap(QtGui.QPixmap(imagesPath + str(totalQuestions%10) + ".png"))
        self.totalQuestionsDigit1.setScaledContents(True)
        self.totalQuestionsDigit1.setObjectName("totalQuestionsDigit1")

        self.slashTitle = QtWidgets.QLabel(results)
        self.slashTitle.setGeometry(QtCore.QRect(1225, 150, 50, 100))
        self.slashTitle.setText("")
        self.slashTitle.setPixmap(QtGui.QPixmap(imagesPath + "slash.png"))
        self.slashTitle.setScaledContents(True)
        self.slashTitle.setObjectName("slashTitle")
        
        self.percentageHeader = QtWidgets.QLabel(results)
        self.percentageHeader.setGeometry(QtCore.QRect(200, 300, 300, 70))
        self.percentageHeader.setText("")
        self.percentageHeader.setPixmap(QtGui.QPixmap(imagesPath + "percentage.png"))
        self.percentageHeader.setScaledContents(True)
        self.percentageHeader.setObjectName("percentageHeader")
        
        self.percentageLabel = QtWidgets.QTextBrowser(results)
        self.percentageLabel.setGeometry(QtCore.QRect(200, 400, 300, 70))
        self.percentageLabel.setText("")
        self.percentageLabel.setStyleSheet("border: 1px solid #000000;\n"
"border-image: url(" + str(imagesPath) + "metal.png) 0 0 0 0 stretch stretch;")
        self.percentageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.percentageLabel.setObjectName("percentageLabel")
        
        self.retryButton.raise_()
        self.reviseButton.raise_()
        self.resultsTitle.raise_()
        self.correctnessHeader.raise_()
        self.questionHeader.raise_()
        self.leaderboardButton.raise_()
        self.percentageHeader.raise_()
        self.percentageLabel.raise_()


        '''
        results.setFrameShape(QtWidgets.QFrame.StyledPanel)
        results.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayout = QtWidgets.QVBoxLayout(results)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(results)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(results)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.pushButton = QtWidgets.QPushButton(results)
        self.pushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(results)
        QtCore.QMetaObject.connectSlotsByName(results)'''

    def retranslateUi(self, results):
        _translate = QtCore.QCoreApplication.translate
        results.setWindowTitle(_translate("results", "Frame"))
        self.label.setText(_translate("results", "Results:"))
        #self.label_2.setText(_translate("results", "Output Results Here."))
        self.pushButton.setText(_translate("results", "Leaderboard"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    results = QtWidgets.QFrame()
    ui = Ui_results()
    ui.setupUi(results)
    results.show()
    sys.exit(app.exec_())
